const state = {
  // 求职端
  register: 'V1/jobhunters/register',
  login: 'V1/jobhunters/login',
  user_details: 'V1/tasks/user_details',
  personals: 'V1/jobhunters/personals',
  work_experience: 'V1/resume/work_experience',
  education_experience: 'V1/resume/education_experience',
  show_education: 'V1/resume/show_education',
  job_intention: 'V1/resume/job_intention',
  show_job: 'V1/resume/show_job',
  show_work: 'V1/resume/show_work',
  delete_work: 'V1/resume/delete_work',
  delete_education: 'V1/resume/delete_education',
  project_experience: 'V1/resume/project_experience',
  show_project: 'V1/resume/show_project',
  delete_job: 'V1/resume/delete_job',
  self_intro: 'V1/resume/self_intro',
  show_self_intro: 'V1/resume/show_self_intro',
  preview: 'V1/resume/preview',
  jobhunter_receive: 'V1/tasks/jobhunter_receive',
  order_process: 'V1/tasks/order_process',
  order_lists: 'V1/jobhunter_orders/order_lists',
  jobhunter_interview: 'V1/jobhunter_orders/jobhunter_interview',
  jobhunter_work: 'V1/jobhunter_orders/jobhunter_work',
  selfinfo: 'V1/jobhunters/selfinfo',
  perfect_degree: 'V1/resume/perfect_degree',
  // common
  SMSs: 'V1/notifications/SMSs',
  taks_lists: 'V1/tasks/lists',
  occupations: 'V1/gongg/occupations',
  majors: 'V1/gongg/majors',
  check_code: 'V1/gongg/check_code',
  carousel: 'V1/gongg/carousel',
  city: 'V1/gongg/city',
  area: 'V1/gongg/area',
  check_phone: 'V1/headhunters/check_phone',
  // 猎头端
  head_details: 'V1/tasks/head_details',
  first_register: 'V1/headhunters/first_register',
  second_register: 'V1/headhunters/second_register',
  // login: 'V1/headhunters/login',
  promotion: 'V1/payment/promotion',
  head_receive: 'V1/tasks/head_receive',
  generalize_code: 'V1/tasks/generalize_code',
  head_cancle: 'V1/tasks/head_cancle',
  balance: 'V1/balance/index',
  application_show: 'V1/balance/application_show',
  application_order: 'V1/balance/application_order',
  withdraw_profile: 'V1/balance/withdraw_profile',
  mytalent_pool: 'V1/headhunters/mytalent_pool',
  // order_lists: 'V1/headhunter_orders/order_lists',
  order_going: 'V1/headhunter_orders/order_going',
  order_problems: 'V1/headhunter_orders/order_problems',
  order_finishs: 'V1/headhunter_orders/order_finishs',
  wxpay: 'V1/payment/wxpay',
  free_pay: 'V1/payment/pay',
  modify: 'V1/headhunters/modify'
};

export default {
  state
};
